spring.application.name = psychoHelp

spring.datasource.url = jdbc:mysql://localhost:3306/psychohelp?createDatabaseIfNotExist=true
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = create